/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expi;

import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel
 */
public class ex03 extends javax.swing.JFrame {
    
    /**
     * Creates new form ex03
     */
    public ex03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScrollCompra = new javax.swing.JScrollPane();
        listaCompra = new javax.swing.JList<>();
        scrollCarrinho = new javax.swing.JScrollPane();
        listaCarrinho = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btmSomar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Compra"));
        listaCompra.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Açúcar - R$:02:25", "Arroz - R$:08:00", "Biscoito - R$:01:75", "Café - R$:03:50", "Catchup - R$:06:00", "Farinha - R$:04:00", "Feijão - R$:05:50", "Leite - R$:01:80", "Macarrão - R$:02:30", "Sal - R$:03:60" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCompra.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ScrollCompra.setViewportView(listaCompra);

        listaCarrinho.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho"));
        listaCarrinho.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollCarrinho.setViewportView(listaCarrinho);

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btmSomar.setText("Somar Carrinho");
        btmSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSomarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Carrinho");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(btmSomar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScrollCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(scrollCarrinho))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmSomar)
                    .addComponent(btnLimpar))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String[] itens = new String[5];
    DefaultListModel<String> modelCompra = new DefaultListModel<>();
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String itemSelected = listaCompra.getSelectedValue();

        if (itemSelected != null) {
            for (int i = 0; i < itens.length; i++) {
                if (itens[i] == null) {
                    itens[i] = itemSelected;
                    modelCompra.addElement(itens[i]);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um item para adicionar no carrinho");
        }
        checkCarrinho();
        listaCarrinho.setModel(modelCompra);
    }//GEN-LAST:event_btnAddActionPerformed

    private void checkCarrinho() {
        boolean validate = false;
        for (String item : itens) {
            if (item == null) {
                validate = true;
                break;
            }
        }
        if (validate == false) {
            JOptionPane.showMessageDialog(this, "O carrinho está cheio");
        }
    }

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String itemSelected = listaCarrinho.getSelectedValue();

        if (itemSelected != null) {
            for (int i = 4; i >= 0; i--) {
                if (itens[i] == itemSelected) {
                    itens[i] = null;
                    modelCompra.removeElementAt(i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um item para remover do carrinho");
        }
        listaCarrinho.setModel(modelCompra);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        for (int i = 0; i < itens.length; i++) {
            itens[i] = null;
        }
        modelCompra.removeAllElements();
        listaCarrinho.setModel(modelCompra);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btmSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSomarActionPerformed
        DecimalFormat fmt = new DecimalFormat("R$ 00.00");
        String[] itensCarrinho = new String[5];
        double somaTotal = 0;

        for (int i = 0; i < listaCarrinho.getModel().getSize(); i++) {
            itensCarrinho[i] = String.valueOf(listaCarrinho.getModel().getElementAt(i));
        }

        for (String item : itensCarrinho) {
            if (item != null) {
                String[] aux = item.split(" ");
                String[] temp = aux[2].split(":");
                double valItem = Double.parseDouble(temp[1] + "." + temp[2]);
                somaTotal += valItem;
            }
        }
        if (somaTotal != 0) {
            JOptionPane.showMessageDialog(this, "O valor da sua compra é: " + fmt.format(somaTotal));
        } else {
            JOptionPane.showMessageDialog(this, "O carrinho está vazio");
        }
    }//GEN-LAST:event_btmSomarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex03.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex03.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex03.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex03.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollCompra;
    private javax.swing.JButton btmSomar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> listaCarrinho;
    private javax.swing.JList<String> listaCompra;
    private javax.swing.JScrollPane scrollCarrinho;
    // End of variables declaration//GEN-END:variables
}
