/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expi;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel
 */
public class ex04 extends javax.swing.JFrame {

    /**
     * Creates new form ex04
     */
    public ex04() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario01 = new javax.swing.JLabel();
        txtUsuario01 = new javax.swing.JTextField();
        labelUsuario02 = new javax.swing.JLabel();
        txtUsuario02 = new javax.swing.JTextField();
        labelUsuario03 = new javax.swing.JLabel();
        txtUsuario03 = new javax.swing.JTextField();
        labelUsuario04 = new javax.swing.JLabel();
        txtUsuario04 = new javax.swing.JTextField();
        labelUsuario05 = new javax.swing.JLabel();
        txtUsuario05 = new javax.swing.JTextField();
        labelUsuario06 = new javax.swing.JLabel();
        txtUsuario06 = new javax.swing.JTextField();
        labelUsuario07 = new javax.swing.JLabel();
        txtUsuario07 = new javax.swing.JTextField();
        labelUsuario08 = new javax.swing.JLabel();
        txtUsuario08 = new javax.swing.JTextField();
        labelUsuario09 = new javax.swing.JLabel();
        txtUsuario09 = new javax.swing.JTextField();
        labelUsuario10 = new javax.swing.JLabel();
        txtUsuario10 = new javax.swing.JTextField();
        btnResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTitulo.setText("Informe a idade dos usuarios");

        labelUsuario01.setText("Usuario 01:");

        labelUsuario02.setText("Usuario 02:");

        labelUsuario03.setText("Usuario 03:");

        labelUsuario04.setText("Usuario 04:");

        labelUsuario05.setText("Usuario 05:");

        labelUsuario06.setText("Usuario 06:");

        labelUsuario07.setText("Usuario 07:");

        labelUsuario08.setText("Usuario 08:");

        labelUsuario09.setText("Usuario 09:");

        labelUsuario10.setText("Usuario 10:");

        btnResult.setText("Calcular");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelUsuario01)
                                            .addComponent(labelUsuario02)
                                            .addComponent(labelUsuario03)
                                            .addComponent(labelUsuario04)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(labelUsuario05)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuario01, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(txtUsuario02)
                                    .addComponent(txtUsuario03)
                                    .addComponent(txtUsuario04)
                                    .addComponent(txtUsuario05))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelUsuario09, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(labelUsuario10))
                                            .addComponent(labelUsuario08))
                                        .addComponent(labelUsuario07))
                                    .addComponent(labelUsuario06))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuario06)
                            .addComponent(txtUsuario07, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario08, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario09, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtUsuario10, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelTitulo)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario01)
                    .addComponent(txtUsuario01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario06)
                    .addComponent(txtUsuario06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario02)
                    .addComponent(txtUsuario02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario07)
                    .addComponent(txtUsuario07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario03)
                    .addComponent(txtUsuario03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario08)
                    .addComponent(txtUsuario08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario04)
                    .addComponent(txtUsuario04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario09)
                    .addComponent(txtUsuario09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario05)
                    .addComponent(txtUsuario05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario10)
                    .addComponent(txtUsuario10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnResult)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        DecimalFormat fmt = new DecimalFormat("00");
        boolean notEmpty = isNotEmpty();
        
        float maior = 0;
        float menor = Float.MAX_VALUE;
        float media = 0;
        float mediaTotal = 0;
        
        if(isNumeric(txtUsuario01.getText(), txtUsuario02.getText(), txtUsuario03.getText(), txtUsuario04.getText(), txtUsuario05.getText(), 
                    txtUsuario06.getText(), txtUsuario07.getText(), txtUsuario08.getText(), txtUsuario09.getText(), txtUsuario10.getText())){
            List<Float> idades = new ArrayList();
            
            idades.add(convertStringToNumber(txtUsuario01.getText()));
            idades.add(convertStringToNumber(txtUsuario02.getText()));
            idades.add(convertStringToNumber(txtUsuario03.getText()));
            idades.add(convertStringToNumber(txtUsuario04.getText()));
            idades.add(convertStringToNumber(txtUsuario05.getText()));
            idades.add(convertStringToNumber(txtUsuario06.getText()));
            idades.add(convertStringToNumber(txtUsuario07.getText()));
            idades.add(convertStringToNumber(txtUsuario08.getText()));
            idades.add(convertStringToNumber(txtUsuario09.getText()));
            idades.add(convertStringToNumber(txtUsuario10.getText()));
                        
            for (Float idade : idades) {
                if (idade > maior){
                    maior = idade;
                }
                if (idade < menor){
                    menor = idade;
                }
                media += idade;
                mediaTotal = media / idades.size();
            } 
            JOptionPane.showMessageDialog(this, "A maior idade é: " + fmt.format(maior) + 
                    "\n" + "A menor idade é: " + fmt.format(menor) + 
                    "\n" + "A media de idade é: " + mediaTotal);
        }
    }//GEN-LAST:event_btnResultActionPerformed
    
    private boolean isNotEmpty(){
        if(!(txtUsuario01.getText().isEmpty()) && !(txtUsuario02.getText().isEmpty()) &&
           !(txtUsuario03.getText().isEmpty()) && !(txtUsuario04.getText().isEmpty()) &&
           !(txtUsuario05.getText().isEmpty()) && !(txtUsuario06.getText().isEmpty()) &&
           !(txtUsuario07.getText().isEmpty()) && !(txtUsuario08.getText().isEmpty()) &&
           !(txtUsuario09.getText().isEmpty()) && !(txtUsuario10.getText().isEmpty())){
            return true;
        }
        return false;
    }
    
   public boolean isNumeric(String val01, String val02, String val03, String val04, String val05,
                            String val06, String val07, String val08, String val09, String val10) {
        try {
            if (isNotEmpty()){
                Float.parseFloat(val01);
                Float.parseFloat(val02);
                Float.parseFloat(val03);
                Float.parseFloat(val04);
                Float.parseFloat(val05);
                Float.parseFloat(val06);
                Float.parseFloat(val07);
                Float.parseFloat(val08);
                Float.parseFloat(val09);
                Float.parseFloat(val10);              
                return true;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Insira apenas numeros");
        }
        return false;
    }
    
    private float convertStringToNumber(String val) {
        return Float.parseFloat(val);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario01;
    private javax.swing.JLabel labelUsuario02;
    private javax.swing.JLabel labelUsuario03;
    private javax.swing.JLabel labelUsuario04;
    private javax.swing.JLabel labelUsuario05;
    private javax.swing.JLabel labelUsuario06;
    private javax.swing.JLabel labelUsuario07;
    private javax.swing.JLabel labelUsuario08;
    private javax.swing.JLabel labelUsuario09;
    private javax.swing.JLabel labelUsuario10;
    private javax.swing.JTextField txtUsuario01;
    private javax.swing.JTextField txtUsuario02;
    private javax.swing.JTextField txtUsuario03;
    private javax.swing.JTextField txtUsuario04;
    private javax.swing.JTextField txtUsuario05;
    private javax.swing.JTextField txtUsuario06;
    private javax.swing.JTextField txtUsuario07;
    private javax.swing.JTextField txtUsuario08;
    private javax.swing.JTextField txtUsuario09;
    private javax.swing.JTextField txtUsuario10;
    // End of variables declaration//GEN-END:variables
}
