/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expi;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel
 */
public class ex05 extends javax.swing.JFrame {
    /**
     * Creates new form ex05
     */
    public ex05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoJogo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioPedra = new javax.swing.JRadioButton();
        radioPapel = new javax.swing.JRadioButton();
        radioTesoura = new javax.swing.JRadioButton();
        labelPlacar = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();
        labelComputador = new javax.swing.JLabel();
        txtComputador = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        labelOpcoes = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupoJogo.add(radioPedra);
        radioPedra.setText("Pedra");

        grupoJogo.add(radioPapel);
        radioPapel.setText("Papel");

        grupoJogo.add(radioTesoura);
        radioTesoura.setText("Tesoura");

        labelPlacar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPlacar.setText("Placar:");

        labelUsuario.setText("Usuario:");

        labelComputador.setText("Computador:");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setText("Pedra, papel e tesoura");

        labelOpcoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelOpcoes.setText("Escolha sua jogada:");

        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPlacar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioPedra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioPapel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioTesoura))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelOpcoes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelComputador))
                            .addComponent(btnJogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComputador, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelOpcoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPedra)
                    .addComponent(radioPapel)
                    .addComponent(radioTesoura))
                .addGap(14, 14, 14)
                .addComponent(labelPlacar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelComputador)
                    .addComponent(txtComputador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnJogar)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int pontosUsuario = 0;
    int pontosComputador = 0;
    int numUsuario = 0;

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        Random rdn = new Random();
        int numComputador = rdn.nextInt(3) + 1;

        if (!(radioPapel.isSelected()) && !(radioPedra.isSelected()) && !(radioTesoura.isSelected())) {
            JOptionPane.showMessageDialog(this, "Selecione alguma jogada");
        } else {
            recebeNumUsuario();

            if (this.numUsuario == numComputador) {
                JOptionPane.showMessageDialog(this, "Empate!");
            } else if (this.numUsuario - numComputador == -1 || this.numUsuario - numComputador == 2) {
                this.pontosUsuario++;
            } else {
                this.pontosComputador++;
            }
            txUsuario.setText("" + this.pontosUsuario);
            txtComputador.setText("" + this.pontosComputador);
        }

    }//GEN-LAST:event_btnJogarActionPerformed

    // 1 = Papel; 2 = Pedra; 3 = Tesoura
    private void recebeNumUsuario() {
        if (radioPapel.isSelected()) {
            this.numUsuario = 1;
        } else if (radioPedra.isSelected()) {
            this.numUsuario = 2;
        } else if (radioTesoura.isSelected()) {
            this.numUsuario = 3;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.ButtonGroup grupoJogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelComputador;
    private javax.swing.JLabel labelOpcoes;
    private javax.swing.JLabel labelPlacar;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JRadioButton radioPapel;
    private javax.swing.JRadioButton radioPedra;
    private javax.swing.JRadioButton radioTesoura;
    private javax.swing.JTextField txUsuario;
    private javax.swing.JTextField txtComputador;
    // End of variables declaration//GEN-END:variables
}
