package br.senac.view;

import br.senac.controller.ServicoAutenticacao;
import br.senac.controller.ServicoDaoCategoria;
import br.senac.controller.ServicoDaoProduto;
import br.senac.db.utils.ManipularImagem;
import br.senac.exception.DaoException;
import br.senac.model.CategoriaProduto;
import br.senac.model.Funcionario;
import br.senac.model.ItemVenda;
import br.senac.model.Produto;
import br.senac.model.TipoSegmento;
import br.senac.model.Venda;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaFuncionario extends javax.swing.JFrame {

    FinalizaVenda telaVenda = null;
    Funcionario userLogged = null;
    Login login = null;

    BufferedImage imagem = null;

    public TelaFuncionario() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Vendedor");

        userLogged = ServicoAutenticacao.getInstance().getUserLoged();

        if (userLogged == null) {
            this.dispose();
            login.setVisible(true);
            login.toFront();
        }

        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dtConvertida = dateFormat.format(date);
        lblUser.setText(userLogged.getNome());
        lblData.setText(dtConvertida);

        jcCategoria.addItem("Todos");
        getCategoria();

        File imgPadrao = new File("branco.png");
        imagem = ManipularImagem.setImagemDimensao(imgPadrao.getAbsolutePath(), 146, 170);
        byte[] imgAux = ManipularImagem.getImgBytes(imagem);
        ManipularImagem.exibiImagemLabel(imgAux, lblImg);
    }

    public void getCategoria() {
        List<CategoriaProduto> listaCategoria = null;
        try {
            listaCategoria = ServicoDaoCategoria.getIstance().listarCategoria();

            for (CategoriaProduto c : listaCategoria) {
                jcCategoria.addItem(c.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nenhuma Categoria Cadastrada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jtFooter = new javax.swing.JToolBar();
        lblInfoUser = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        padding = new javax.swing.JLabel();
        lblInfoData = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        padding02 = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jpCategoria = new javax.swing.JPanel();
        jcCategoria = new javax.swing.JComboBox<>();
        jpInforProduto = new javax.swing.JPanel();
        jpImagem = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        lblSegmento = new javax.swing.JLabel();
        txtSegmento = new javax.swing.JTextField();
        lblTamanho = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        lblPreço = new javax.swing.JLabel();
        txtPreço = new javax.swing.JTextField();
        btnAddCarrinho = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jsQuant = new javax.swing.JSpinner();
        lblQuant = new javax.swing.JLabel();
        jpListaProduto = new javax.swing.JPanel();
        gridProdutos = new javax.swing.JPanel();
        jpListaCompra = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListaCompra = new javax.swing.JTable();
        jpFinalizar = new javax.swing.JPanel();
        lblTotalItens = new javax.swing.JLabel();
        txtTotalItens = new javax.swing.JTextField();
        lblTotalCompra = new javax.swing.JLabel();
        txtTotalCompra = new javax.swing.JTextField();
        btnCancelarCompra = new javax.swing.JButton();
        btnReceberCompra = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtFooter.setFloatable(false);
        jtFooter.setRollover(true);

        lblInfoUser.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblInfoUser.setText("Usuario: ");
        lblInfoUser.setPreferredSize(new java.awt.Dimension(43, 20));
        jtFooter.add(lblInfoUser);

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblUser.setPreferredSize(new java.awt.Dimension(34, 30));
        jtFooter.add(lblUser);
        lblUser.getAccessibleContext().setAccessibleName("lbl");

        padding.setText("    |    ");
        jtFooter.add(padding);

        lblInfoData.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblInfoData.setText("Data: ");
        lblInfoData.setToolTipText("");
        jtFooter.add(lblInfoData);
        jtFooter.add(lblData);

        padding02.setText("   |   ");
        jtFooter.add(padding02);

        lblSair.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblSair.setText("Sair:");
        jtFooter.add(lblSair);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senac/imagens/exit.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jtFooter.add(jButton1);

        jpCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N

        jcCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcCategoriaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpCategoriaLayout = new javax.swing.GroupLayout(jpCategoria);
        jpCategoria.setLayout(jpCategoriaLayout);
        jpCategoriaLayout.setHorizontalGroup(
            jpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcCategoria, 0, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpCategoriaLayout.setVerticalGroup(
            jpCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpInforProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N

        jpImagem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagem Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpImagemLayout = new javax.swing.GroupLayout(jpImagem);
        jpImagem.setLayout(jpImagemLayout);
        jpImagemLayout.setHorizontalGroup(
            jpImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );
        jpImagemLayout.setVerticalGroup(
            jpImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNome.setText("Nome:");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblMarca.setText("Marca:");

        lblMaterial.setText("Material:");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQuantidade.setText("Estoque:");

        txtNome.setEditable(false);

        txtMarca.setEditable(false);

        txtMateria.setEditable(false);

        txtQuantidade.setEditable(false);
        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(255, 51, 0));

        lblSegmento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSegmento.setText("Segmento:");

        txtSegmento.setEditable(false);

        lblTamanho.setText("Tamanho:");

        txtTamanho.setEditable(false);

        lblPreço.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPreço.setText("Preço:");

        txtPreço.setEditable(false);
        txtPreço.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPreço.setForeground(new java.awt.Color(255, 0, 0));

        btnAddCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnAddCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senac/imagens/plus.png"))); // NOI18N
        btnAddCarrinho.setText("  Adicionar ao Carrinho");
        btnAddCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarrinhoActionPerformed(evt);
            }
        });

        lblCodigo.setText("Codigo:");

        txtCodigo.setEditable(false);

        jsQuant.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jsQuant.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));

        lblQuant.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQuant.setText("Quantidade:");

        javax.swing.GroupLayout jpInforProdutoLayout = new javax.swing.GroupLayout(jpInforProduto);
        jpInforProduto.setLayout(jpInforProdutoLayout);
        jpInforProdutoLayout.setHorizontalGroup(
            jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInforProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInforProdutoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpInforProdutoLayout.createSequentialGroup()
                                    .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpInforProdutoLayout.createSequentialGroup()
                                            .addComponent(lblSegmento)
                                            .addGap(303, 303, 303)
                                            .addComponent(lblMaterial))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInforProdutoLayout.createSequentialGroup()
                                            .addComponent(lblTamanho)
                                            .addGap(310, 310, 310)
                                            .addComponent(lblCodigo)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMateria)
                                        .addComponent(txtCodigo)))
                                .addGroup(jpInforProdutoLayout.createSequentialGroup()
                                    .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpInforProdutoLayout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(lblNome))
                                        .addGroup(jpInforProdutoLayout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(lblMarca)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMarca)
                                        .addComponent(txtNome)
                                        .addGroup(jpInforProdutoLayout.createSequentialGroup()
                                            .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(jpInforProdutoLayout.createSequentialGroup()
                                .addComponent(lblQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQuant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(jpInforProdutoLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnAddCarrinho)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpInforProdutoLayout.setVerticalGroup(
            jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInforProdutoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInforProdutoLayout.createSequentialGroup()
                .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegmento)
                    .addComponent(txtSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaterial)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanho)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInforProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade)
                    .addComponent(lblPreço)
                    .addComponent(txtPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuant)
                    .addComponent(jsQuant))
                .addGap(18, 18, 18)
                .addComponent(btnAddCarrinho)
                .addGap(25, 25, 25))
        );

        jpListaProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N

        gridProdutos.setLayout(new java.awt.GridLayout(0, 4));

        javax.swing.GroupLayout jpListaProdutoLayout = new javax.swing.GroupLayout(jpListaProduto);
        jpListaProduto.setLayout(jpListaProdutoLayout);
        jpListaProdutoLayout.setHorizontalGroup(
            jpListaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gridProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpListaProdutoLayout.setVerticalGroup(
            jpListaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gridProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpListaCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jtListaCompra.setAutoCreateRowSorter(true);
        jtListaCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jtListaCompra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jtListaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "COD", "PRODUTO", "QUANT", "PRECO UNI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaCompra.setGridColor(new java.awt.Color(255, 255, 255));
        jtListaCompra.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jtListaCompra);

        javax.swing.GroupLayout jpListaCompraLayout = new javax.swing.GroupLayout(jpListaCompra);
        jpListaCompra.setLayout(jpListaCompraLayout);
        jpListaCompraLayout.setHorizontalGroup(
            jpListaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListaCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jpListaCompraLayout.setVerticalGroup(
            jpListaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaCompraLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpFinalizar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N

        lblTotalItens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalItens.setText("Itens:");

        txtTotalItens.setEditable(false);
        txtTotalItens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotalItens.setForeground(new java.awt.Color(255, 0, 0));

        lblTotalCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalCompra.setText("Total:");

        txtTotalCompra.setEditable(false);
        txtTotalCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotalCompra.setForeground(new java.awt.Color(255, 0, 0));

        btnCancelarCompra.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnCancelarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senac/imagens/cancel_24.png"))); // NOI18N
        btnCancelarCompra.setText("  Cancelar Pedido");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        btnReceberCompra.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnReceberCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senac/imagens/money-cash-pay.png"))); // NOI18N
        btnReceberCompra.setText("  Receber Pagamento");
        btnReceberCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberCompraActionPerformed(evt);
            }
        });

        btnRemoveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senac/imagens/cancel_16.png"))); // NOI18N
        btnRemoveItem.setText("   Remover");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFinalizarLayout = new javax.swing.GroupLayout(jpFinalizar);
        jpFinalizar.setLayout(jpFinalizarLayout);
        jpFinalizarLayout.setHorizontalGroup(
            jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFinalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpFinalizarLayout.createSequentialGroup()
                        .addComponent(lblTotalCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalCompra))
                    .addGroup(jpFinalizarLayout.createSequentialGroup()
                        .addComponent(lblTotalItens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalItens, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveItem)))
                .addGap(157, 157, 157)
                .addComponent(btnCancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReceberCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpFinalizarLayout.setVerticalGroup(
            jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFinalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFinalizarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalItens)
                            .addComponent(txtTotalItens, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRemoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCompra)
                    .addComponent(txtTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jpFinalizarLayout.createSequentialGroup()
                .addGroup(jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceberCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpListaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpListaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpInforProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jpCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpListaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpInforProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpListaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReceberCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberCompraActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtListaCompra.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum Item no Carrinho", "Sem Produtos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (telaVenda != null) {
            telaVenda.dispose();
        }

        Venda venda = new Venda();
        List<ItemVenda> listaVenda = null;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (listaVenda == null) {
                listaVenda = new ArrayList<>();
            }
            ItemVenda item = new ItemVenda();
            Produto p = new Produto();

            p.setIdProduto((int) model.getValueAt(i, 0));
            p.setCodigo((int) model.getValueAt(i, 1));
            p.setNome(model.getValueAt(i, 2).toString());
            p.setPrecoUni((float) model.getValueAt(i, 4));

            item.setQuant((int) model.getValueAt(i, 3));
            item.setPrecoUni(p.getPrecoUni());
            item.setProduto(p);

            listaVenda.add(item);
        }
        venda.setListaItensVendidos(listaVenda);
        venda.setFuncionario(userLogged);

        telaVenda = new FinalizaVenda();
        telaVenda.setVisible(true);
        telaVenda.toFront();

        telaVenda.setVenda(venda);
        telaVenda.setTelaUser(this);
    }//GEN-LAST:event_btnReceberCompraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Deseja sair do sistema ?", "Sair", JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_OPTION) {
            ServicoAutenticacao.getInstance().logout(this);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private Produto tempProduto = null;
    private void jcCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcCategoriaItemStateChanged
        try {

            int id = jcCategoria.getSelectedIndex();

            List<Produto> produtos = ServicoDaoProduto.getIstance().filtroProduto(id);

            if (produtos == null) {
                gridProdutos.removeAll();
                return;
            }

            gridProdutos.removeAll();
            for (Produto produto : produtos) {
                JButton button = new JButton();
                button.setText(produto.getNome());

                ActionListener listener = new ActionListener() {
                    public void actionPerformed(ActionEvent ae) {
                        infoProduto(produto.getIdProduto());
                        tempProduto = produto;
                    }
                };
                button.addActionListener(listener);
                gridProdutos.add(button);
            }
            gridProdutos.revalidate();
            gridProdutos.repaint();

        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou resultados ", "Sem resultados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jcCategoriaItemStateChanged

    int size = 0;
    float valTotal = 0;
    List<Produto> listaVenda = null;
    private void btnAddCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarrinhoActionPerformed
        int quant = (int) jsQuant.getValue();
        int estoque = Integer.parseInt(txtQuantidade.getText());

        if (tempProduto != null) {
            if (listaVenda == null) {
                listaVenda = new ArrayList<>();
            }
            if (quant == 0) {
                JOptionPane.showMessageDialog(rootPane, "Informe uma quantidade", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (quant > tempProduto.getQuant() || quant > estoque) {
                JOptionPane.showMessageDialog(rootPane, "Quantidade superior ao estoque", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jtListaCompra.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                if ((int) model.getValueAt(i, 1) == tempProduto.getCodigo()) {
                    JOptionPane.showMessageDialog(rootPane, "Produto já inserido!", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            model.addRow(new Object[]{
                tempProduto.getIdProduto(),
                tempProduto.getCodigo(),
                tempProduto.getNome(),
                quant,
                tempProduto.getPrecoUni(),});

            valTotal += tempProduto.getPrecoUni() * quant;
            size++;
            updateValueTotal(size, valTotal);

            listaVenda.add(tempProduto);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um produto ", "Sem resultados", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddCarrinhoActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed

        try {
            DefaultTableModel model = (DefaultTableModel) jtListaCompra.getModel();
            int index = jtListaCompra.getSelectedRow();
            float val = Float.parseFloat(jtListaCompra.getValueAt(index, 4).toString());

            model.removeRow(index);
            listaVenda.remove(index);
            valTotal -= val;
            size = model.getRowCount();
            updateValueTotal(model.getRowCount(), valTotal);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione algum produto");
        }

    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        if (listaVenda == null || listaVenda.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nenhuma venda iniciada", "Sem venda", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int resp = JOptionPane.showConfirmDialog(this, "Deseja cancelar Compra ?", "Cancelar", JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_OPTION) {
            clear();
        }

    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    public void clear() {
        DefaultTableModel model = (DefaultTableModel) jtListaCompra.getModel();

        model.setNumRows(0);
        listaVenda.clear();
        tempProduto = null;
        size = 0;
        valTotal = 0;

        byte[] imgAux = ManipularImagem.getImgBytes(imagem);
        ManipularImagem.exibiImagemLabel(imgAux, lblImg);

        resetTnfoProduto();
        updateValueTotal(0, 0);
    }

    private void updateValueTotal(int item, float v) {
        NumberFormat format = new DecimalFormat("#0.00");
        String preco = format.format(v);

        txtTotalItens.setText(item + "");
        txtTotalCompra.setText(preco);
    }

    private void infoProduto(int id) {
        try {
            Produto p = ServicoDaoProduto.getIstance().pegaProdutoById(id);

            TipoSegmento segmento = TipoSegmento.getEnum(p.getSegmento());
            NumberFormat format = new DecimalFormat("#0.00");
            String preco = format.format(p.getPrecoUni());

            txtNome.setText(p.getNome());
            txtMarca.setText(p.getMarca());
            txtSegmento.setText(segmento.toString());
            txtMateria.setText(p.getMaterial());
            txtTamanho.setText(p.getTamanho());
            txtCodigo.setText(p.getCodigo() + "");
            txtQuantidade.setText(p.getQuant() + "");
            txtPreço.setText(preco);
            jsQuant.setValue(0);
            ManipularImagem.exibiImagemLabel(p.getImg(), lblImg);
        } catch (Exception e) {
        }
    }

    private void resetTnfoProduto() {
        txtNome.setText(null);
        txtMarca.setText(null);
        txtSegmento.setText(null);
        txtMateria.setText(null);
        txtTamanho.setText(null);
        txtCodigo.setText(null);
        txtQuantidade.setText(null);
        txtPreço.setText(null);
        jsQuant.setValue(0);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCarrinho;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnReceberCompra;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JPanel gridProdutos;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JPanel jpCategoria;
    private javax.swing.JPanel jpFinalizar;
    private javax.swing.JPanel jpImagem;
    private javax.swing.JPanel jpInforProduto;
    private javax.swing.JPanel jpListaCompra;
    private javax.swing.JPanel jpListaProduto;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JSpinner jsQuant;
    private javax.swing.JToolBar jtFooter;
    private javax.swing.JTable jtListaCompra;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblInfoData;
    private javax.swing.JLabel lblInfoUser;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreço;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblSegmento;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTotalCompra;
    private javax.swing.JLabel lblTotalItens;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel padding;
    private javax.swing.JLabel padding02;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreço;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSegmento;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JTextField txtTotalCompra;
    private javax.swing.JTextField txtTotalItens;
    // End of variables declaration//GEN-END:variables
}
