package br.com.fabio.ui.principal;

import br.com.fabio.ui.clientes.TelaCadastrarCliente;
import br.com.fabio.ui.clientes.TelaConsultarClientes;
import br.com.fabio.ui.quartos.TelaCadastrarQuarto;
import br.com.fabio.ui.quartos.TelaConsultarQuartos;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fabio
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private Image image;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {        
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
        this.setSize(screenSize.width,200);
        this.setResizable(false);
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            private BufferedImage image;
            {
                try {
                    image = ImageIO.read(new File("src/resources/hotel.jpg"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g.create();
                int tileWidth = image.getWidth();
                int tileHeight = image.getHeight();
                for (int y = 0; y < getHeight(); y += tileHeight) {
                    for (int x = 0; x < getWidth(); x += tileWidth) {
                        g2d.drawImage(image, x, y, this);
                    }
                }
                g2d.dispose();
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Master");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Clientes");

        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Consultar Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quartos");

        jMenuItem3.setText("Cadastrar Quartos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Consultar Quartos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    TelaCadastrarCliente telaCadastrarCliente = null;
    TelaConsultarClientes telaConsultarCliente = null;
    TelaCadastrarQuarto telaCadastrarQuarto = null;
    TelaConsultarQuartos telaConsultarQuarto = null;
            
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (telaCadastrarCliente == null || !telaCadastrarCliente.isDisplayable()) {
            telaCadastrarCliente = new TelaCadastrarCliente();
            telaCadastrarCliente.pack();
            telaCadastrarCliente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaCadastrarCliente.setLocationRelativeTo(null);
            telaCadastrarCliente.setVisible(true);
        }
        telaCadastrarCliente.toFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (telaConsultarCliente == null || !telaConsultarCliente.isDisplayable()) {
            telaConsultarCliente = new TelaConsultarClientes();
            telaConsultarCliente.pack();
            telaConsultarCliente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaConsultarCliente.setLocationRelativeTo(null);
            telaConsultarCliente.setVisible(true);
        }
        telaConsultarCliente.toFront();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (telaCadastrarQuarto == null || !telaCadastrarQuarto.isDisplayable()) {
            telaCadastrarQuarto = new TelaCadastrarQuarto();
            telaCadastrarQuarto.pack();
            telaCadastrarQuarto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaCadastrarQuarto.setLocationRelativeTo(null);
            telaCadastrarQuarto.setVisible(true);
        }
        telaCadastrarQuarto.toFront();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (telaConsultarQuarto == null || !telaConsultarQuarto.isDisplayable()) {
            telaConsultarQuarto = new TelaConsultarQuartos();
            telaConsultarQuarto.pack();
            telaConsultarQuarto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaConsultarQuarto.setLocationRelativeTo(null);
            telaConsultarQuarto.setVisible(true);
        }
        telaConsultarQuarto.toFront();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                              
                new TelaPrincipal().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
